1. Import the numpy package under the name np (★☆☆)
2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np

print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    

3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [9]:
print(null_vector.size * null_vector.itemsize, "bytes")

80 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 

In [12]:
arr_range=np.arange(10,50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 8. Reverse a vector (first element becomes last) 

In [13]:
arr_range=arr_range[::-1]
print(arr_range)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [14]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
arr=np.nonzero([1,2,3,0,0,4,0])
print(arr)

(array([0, 1, 2, 5], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)

In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.27371617 0.84629506 0.0819306 ]
  [0.13366971 0.86802549 0.21584254]
  [0.55415819 0.42648825 0.13907984]]

 [[0.68962496 0.45804089 0.97760117]
  [0.97306163 0.86815539 0.77079594]
  [0.19432024 0.11261971 0.42893832]]

 [[0.67947442 0.96688695 0.89507715]
  [0.95837389 0.60276412 0.99279365]
  [0.45187556 0.22276746 0.86489418]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
arr=np.random.random((10,10))
print(arr)
arr_max, arr_min=arr.max(), arr.min()
print(arr_max,arr_min)

[[0.4404049  0.2345542  0.22679863 0.59271887 0.80472314 0.63438656
  0.59654786 0.51687211 0.6064254  0.1968896 ]
 [0.26986694 0.67663752 0.38100322 0.74680261 0.16926986 0.76848849
  0.08847352 0.79425115 0.29690963 0.51583709]
 [0.12407202 0.49384248 0.68699233 0.31586736 0.88595422 0.83901344
  0.35449525 0.26525992 0.903567   0.75792493]
 [0.20738221 0.25282847 0.59551031 0.88259666 0.61014292 0.24209496
  0.75292195 0.30003857 0.50488118 0.09012369]
 [0.53550086 0.97099211 0.16872517 0.4783106  0.59927472 0.91656065
  0.22216216 0.80378069 0.89025158 0.50755055]
 [0.03450483 0.83081204 0.08020883 0.84525078 0.11009637 0.55568763
  0.44610892 0.6641235  0.00499742 0.46790369]
 [0.5312594  0.60434553 0.8938811  0.64655054 0.75505014 0.54413477
  0.98992578 0.14124552 0.92164112 0.22294824]
 [0.73178815 0.78557833 0.83373246 0.28715704 0.78048117 0.59039489
  0.4869561  0.73152374 0.2817498  0.919436  ]
 [0.32745517 0.70588456 0.38614815 0.48997745 0.49809866 0.14543805
  0.99413232

14.  Create a random vector of size 30 and find the mean value 

In [25]:
arr=np.random.random(30)
print(arr)
arr_mean=arr.mean()
print(arr_mean)

[0.70069121 0.87982001 0.0883828  0.30791313 0.20457196 0.78076888
 0.85412706 0.38169013 0.56852131 0.47731512 0.81121461 0.6461879
 0.74412025 0.30560411 0.03873063 0.73540852 0.3070355  0.6087471
 0.76779431 0.1270935  0.82237687 0.52478042 0.3173319  0.46056736
 0.37958529 0.91354656 0.46722517 0.48609511 0.98321262 0.30939173]
0.5333283683508503


 15. Create a 2d array with 1 on the border and 0 inside

In [26]:
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? 

In [28]:
arr = np.ones((6,6))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
arr=np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [32]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


 21. Create a checkerboard 8x8 matrix using the tile function

In [34]:
arr = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 22. Normalize a 5x5 random matrix 

In [36]:
arr= np.random.random((5,5))
arr=(arr - np.mean(arr) / (np.std (arr)))
print(arr)

[[-1.60135233 -0.75591933 -1.36310807 -1.50373916 -1.14981789]
 [-1.38057753 -1.54837095 -1.48663948 -1.35521313 -1.38173385]
 [-0.98629932 -1.10461478 -1.21901851 -1.3248297  -0.85989613]
 [-0.73266249 -1.31476961 -1.34548782 -0.98213992 -1.2342822 ]
 [-0.89412327 -0.79448521 -1.70548427 -1.62131932 -1.47554213]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
arr1=np.ones((5,3))
arr2=np.ones((3,2))
prd=np.dot(arr1,arr2)
print(prd)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
arr=np.arange(11)
arr[(3<arr) & (arr < 8)] *=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


28. What are the result of the following expressions? (★☆☆)

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ? (★☆☆)

In [52]:
arr = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[ 6.  5. -9. -4. -9. -6. -1. 10.  4. -9.]


30. How to find common values between two arrays? (★☆☆)

In [53]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[0 2 4 5 7 8]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

32. Is the following expressions true? (★☆☆)

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

print("today:",yesterday, '\n','today',today, '\n', 'tomorrow', tomorrow)

today: 2024-02-12 
 today 2024-02-13 
 tomorrow 2024-02-14


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
dates_of_jul2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(dates_of_jul2016)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
A = np.ones(4)*1
B = np.ones(4)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5, -1.5])

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
arr = np.random.uniform(0,10,10)
print(arr - arr%1)
print(arr // 1)
print(np.floor(arr))
print(arr.astype(int))
print(np.trunc(arr))

[2. 0. 8. 8. 3. 4. 1. 8. 4. 8.]
[2. 0. 8. 8. 3. 4. 1. 8. 4. 8.]
[2. 0. 8. 8. 3. 4. 1. 8. 4. 8.]
[2 0 8 8 3 4 1 8 4 8]
[2. 0. 8. 8. 3. 4. 1. 8. 4. 8.]


 37. Create a 5x5 matrix with row values ranging from 0 to

In [12]:
arr=np.zeros((5,5))
arr +=np.arange(5)
print(arr)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [14]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(),dtype=float,count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [15]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
print(arr)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. Create a random vector of size 10 and sort it (★★☆)

In [17]:
arr=np.random.random(10)
arr.sort()
print(arr)

[0.05822766 0.0991555  0.2439287  0.28471003 0.33384201 0.41234336
 0.55737229 0.6160117  0.85852293 0.97693976]


41. How to sum a small array faster than np.sum? (★★☆)

In [18]:
Z = np.arange(10)
np.add.reduce(Z)

45

42. Consider two random array A and B, check if they are equal (★★☆)

In [25]:
arrA=np.random.randint(0,2,5)
arrB=np.random.randint(0,2,5)

is_equal = np.array_equal(arrA,arrB)
print(is_equal)

False


43. Make an array immutable (read-only) (★★☆)

In [26]:
arr = np.zeros(10)
arr.flags.writeable = False
arr[0] = 1

ValueError: assignment destination is read-only

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [27]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.91719744 0.29361756 0.79518657 0.98371834 0.85817511 0.62919898
 0.86959683 0.50005764 0.8914067  0.48997496]
[0.02005213 0.90940062 1.51936746 1.02248322 0.53977527 0.79867548
 0.93514456 1.24105201 1.44575696 1.38981015]


45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [29]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.10658622 0.25216893 0.78679285 0.82251974 0.44929072 0.36863576
 0.78239979 0.01013576 0.         0.83012449]


46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [31]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [32]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [33]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. How to print all the values of an array? (★★☆)

In [34]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((40,40))
print(arr)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [35]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

49


51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [36]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

C:\Users\PC\AppData\Local\Temp\ipykernel_3432\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [37]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.22808936 0.47565972 0.37474464 0.70792795 0.40173028
  0.65289809 0.39709703 0.18767716 0.70122052]
 [0.22808936 0.         0.68017048 0.48117532 0.57596639 0.36319407
  0.8474182  0.43342743 0.35739402 0.64665953]
 [0.47565972 0.68017048 0.         0.33825545 0.92803725 0.59288815
  0.18265652 0.47421079 0.52222356 0.78540421]
 [0.37474464 0.48117532 0.33825545 0.         0.59057797 0.2643593
  0.44062633 0.13674213 0.53020475 0.45685425]
 [0.70792795 0.57596639 0.92803725 0.59057797 0.         0.3439217
  1.01923413 0.45398609 0.89048655 0.24696491]
 [0.40173028 0.36319407 0.59288815 0.2643593  0.3439217  0.
  0.70490211 0.13520606 0.58934337 0.30103988]
 [0.65289809 0.8474182  0.18265652 0.44062633 1.01923413 0.70490211
  0.         0.57365238 0.70444819 0.84141866]
 [0.39709703 0.43342743 0.47421079 0.13674213 0.45398609 0.13520606
  0.57365238 0.         0.57601    0.3384688 ]
 [0.18767716 0.35739402 0.52222356 0.53020475 0.89048655 0.58934337
  0.70444819 0.57601  

53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [2]:
import numpy as np
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[56 81 54 37 18 41  3  6 94 54]


54. How to read the following file? (★★☆)
    ```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [8]:
Z = np.arange(4).reshape(2,2)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3


56. Generate a generic 2D Gaussian-like array (★★☆)

In [9]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. How to randomly place p elements in a 2D array? (★★☆)

In [11]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. Subtract the mean of each row of a matrix (★★☆)

In [12]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[ 0.04495384  0.39105627 -0.18340499  0.09155066 -0.11673937 -0.37758591
  -0.22656638  0.35054414  0.13337223 -0.10718049]
 [-0.40069192  0.01491789  0.1415668  -0.4667343   0.47112845  0.38054364
   0.50122258 -0.17441251 -0.10991044 -0.3576302 ]
 [-0.12759978  0.51976545  0.56501504 -0.36457241 -0.42077222  0.07097943
  -0.33854154 -0.39802025  0.13403492  0.35971137]
 [-0.28043299 -0.1091323   0.42768747 -0.20020545  0.41313441 -0.20208689
  -0.28108474 -0.03101526 -0.24157552  0.50471127]
 [-0.05469799  0.22677414 -0.4930445  -0.15330496  0.07149752 -0.32389789
   0.32588827  0.19319284  0.26709608 -0.05950349]]


59. How to sort an array by the nth column? (★★☆)

In [14]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[8 4 9]
 [5 5 8]
 [8 0 0]]
[[8 0 0]
 [8 4 9]
 [5 5 8]]


60. How to tell if a given 2D array has null columns? (★★☆)

In [21]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[0 1 1 2 2 1 2 1 2 1]
 [2 2 2 1 1 0 2 1 0 1]
 [0 1 2 2 0 2 2 0 0 0]]
False


61. Find the nearest value from a given value in an array (★★☆)

In [22]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48782420010480876


62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [23]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. Create an array class that has a name attribute (★★☆)

In [25]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [34]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 3. 3. 2. 2. 4. 3. 3. 4. 4.]


65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)


In [35]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [36]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [37]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[27 60 34 41]
 [66 49 67 55]
 [52 30 50 58]]


68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [38]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.48029267 0.61269013 0.36951202 0.58393798 0.24605621 0.44325494
 0.53049311 0.64111059 0.5070816  0.67912883]


69. How to get the diagonal of a dot product? (★★★)

In [39]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))


np.sum(A * B.T, axis=1)

array([0.63638592, 1.61668309, 0.44848447, 1.43551539, 1.48967592])

70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [40]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [41]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. How to swap two rows of an array? (★★★)


In [42]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [43]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0, 24) ( 0, 90) ( 2,  6) ( 2, 95) ( 3, 71) ( 3, 90) ( 3, 92) ( 3, 99)
 ( 6, 95) ( 7,  8) ( 7, 78) ( 8, 78) (11, 47) (11, 68) (24, 90) (25, 51)
 (25, 60) (26, 49) (26, 71) (43, 44) (43, 94) (44, 94) (45, 85) (45, 87)
 (47, 68) (49, 71) (51, 60) (71, 99) (85, 87) (90, 92)]


74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [44]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


75. How to compute averages using a sliding window over an array? (★★★)

In [47]:
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [48]:
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [49]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-6.30167442e-01,  7.81727446e-01, -1.37852616e-01, -4.77501716e-02,
        4.96553727e-01, -4.78135406e-01,  1.79965823e-01, -2.29920947e-01,
       -7.48872488e-01,  1.32484014e-01, -2.61475499e-01, -7.52729227e-01,
        6.82851255e-02,  6.83422202e-01,  4.23095861e-01,  1.47750910e-01,
       -6.14841409e-01,  8.69245683e-01,  4.29505011e-01,  9.47758479e-02,
        4.25130067e-01,  5.65394841e-02, -4.21030257e-01,  3.32761895e-01,
       -3.98610347e-01,  7.64885840e-02,  8.81348539e-01, -4.69992660e-01,
        2.89212281e-01,  9.67345221e-01,  3.30227063e-01, -3.05696449e-01,
       -2.47582538e-01, -8.23264795e-02, -5.33520861e-01,  1.08076747e-01,
        5.65350359e-02,  8.76042746e-01,  6.90476526e-01,  2.69636574e-01,
       -2.92179810e-01, -8.86000443e-01,  9.79929905e-01, -3.11229435e-01,
       -3.82897614e-01,  9.56346620e-01, -9.77501791e-01, -2.78553204e-01,
       -1.11901809e-01,  3.96881223e-01,  8.99443200e-01,  1.98591314e-01,
       -3.25219753e-01, -

78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [50]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 3.19885696  1.97747846  2.35104741  0.21897136 11.77609394  0.19080281
  2.92475804  2.5340104   8.05411728  5.01323583]


79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [53]:
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. Compute a matrix rank (★★★)

In [54]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


83. How to find the most frequent value i

In [55]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [56]:
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[2 2 0]
   [2 2 1]
   [0 1 4]]

  [[2 0 2]
   [2 1 0]
   [1 4 1]]

  [[0 2 2]
   [1 0 1]
   [4 1 1]]

  [[2 2 2]
   [0 1 1]
   [1 1 2]]

  [[2 2 2]
   [1 1 4]
   [1 2 2]]

  [[2 2 0]
   [1 4 0]
   [2 2 0]]

  [[2 0 4]
   [4 0 2]
   [2 0 0]]

  [[0 4 1]
   [0 2 2]
   [0 0 1]]]


 [[[2 2 1]
   [0 1 4]
   [3 2 2]]

  [[2 1 0]
   [1 4 1]
   [2 2 4]]

  [[1 0 1]
   [4 1 1]
   [2 4 1]]

  [[0 1 1]
   [1 1 2]
   [4 1 1]]

  [[1 1 4]
   [1 2 2]
   [1 1 1]]

  [[1 4 0]
   [2 2 0]
   [1 1 3]]

  [[4 0 2]
   [2 0 0]
   [1 3 0]]

  [[0 2 2]
   [0 0 1]
   [3 0 3]]]


 [[[0 1 4]
   [3 2 2]
   [3 3 4]]

  [[1 4 1]
   [2 2 4]
   [3 4 1]]

  [[4 1 1]
   [2 4 1]
   [4 1 2]]

  [[1 1 2]
   [4 1 1]
   [1 2 0]]

  [[1 2 2]
   [1 1 1]
   [2 0 1]]

  [[2 2 0]
   [1 1 3]
   [0 1 1]]

  [[2 0 0]
   [1 3 0]
   [1 1 4]]

  [[0 0 1]
   [3 0 3]
   [1 4 1]]]


 [[[3 2 2]
   [3 3 4]
   [2 4 0]]

  [[2 2 4]
   [3 4 1]
   [4 0 4]]

  [[2 4 1]
   [4 1 2]
   [0 4 2]]

  [[4 1 1]
   [1 2 0]
   [4 2 3]]

  [[1 1 1]
   

85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [57]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 6 16  8 10  6]
 [16  0 10 12  2]
 [ 8 10  9 42 11]
 [10 12 42  5  4]
 [ 6  2 11  4  3]]
