1. Import the numpy package under the name np (★☆☆)
2. Print the numpy version and the configuration (★☆☆)

In [2]:
import numpy as np

print(np.__version__)
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/PC/miniconda3/envs/datascience\\Library\\lib']
    

3. Create a null vector of size 10 (★☆☆)

In [4]:
null_vector=np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. How to find the memory size of any array (★☆☆)

In [9]:
print(null_vector.size * null_vector.itemsize, "bytes")

80 bytes


5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
arr=np.zeros(10)
arr[4]=1
print(arr)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Create a vector with values ranging from 10 to 49 

In [12]:
arr_range=np.arange(10,50)
print(arr_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


 8. Reverse a vector (first element becomes last) 

In [13]:
arr_range=arr_range[::-1]
print(arr_range)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [14]:
arr=np.arange(9).reshape(3,3)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [15]:
arr=np.nonzero([1,2,3,0,0,4,0])
print(arr)

(array([0, 1, 2, 5], dtype=int64),)


11. Create a 3x3 identity matrix (★☆☆)

In [16]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. Create a 3x3x3 array with random values (★☆☆)

In [17]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.27371617 0.84629506 0.0819306 ]
  [0.13366971 0.86802549 0.21584254]
  [0.55415819 0.42648825 0.13907984]]

 [[0.68962496 0.45804089 0.97760117]
  [0.97306163 0.86815539 0.77079594]
  [0.19432024 0.11261971 0.42893832]]

 [[0.67947442 0.96688695 0.89507715]
  [0.95837389 0.60276412 0.99279365]
  [0.45187556 0.22276746 0.86489418]]]


13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [22]:
arr=np.random.random((10,10))
print(arr)
arr_max, arr_min=arr.max(), arr.min()
print(arr_max,arr_min)

[[0.4404049  0.2345542  0.22679863 0.59271887 0.80472314 0.63438656
  0.59654786 0.51687211 0.6064254  0.1968896 ]
 [0.26986694 0.67663752 0.38100322 0.74680261 0.16926986 0.76848849
  0.08847352 0.79425115 0.29690963 0.51583709]
 [0.12407202 0.49384248 0.68699233 0.31586736 0.88595422 0.83901344
  0.35449525 0.26525992 0.903567   0.75792493]
 [0.20738221 0.25282847 0.59551031 0.88259666 0.61014292 0.24209496
  0.75292195 0.30003857 0.50488118 0.09012369]
 [0.53550086 0.97099211 0.16872517 0.4783106  0.59927472 0.91656065
  0.22216216 0.80378069 0.89025158 0.50755055]
 [0.03450483 0.83081204 0.08020883 0.84525078 0.11009637 0.55568763
  0.44610892 0.6641235  0.00499742 0.46790369]
 [0.5312594  0.60434553 0.8938811  0.64655054 0.75505014 0.54413477
  0.98992578 0.14124552 0.92164112 0.22294824]
 [0.73178815 0.78557833 0.83373246 0.28715704 0.78048117 0.59039489
  0.4869561  0.73152374 0.2817498  0.919436  ]
 [0.32745517 0.70588456 0.38614815 0.48997745 0.49809866 0.14543805
  0.99413232

14.  Create a random vector of size 30 and find the mean value 

In [25]:
arr=np.random.random(30)
print(arr)
arr_mean=arr.mean()
print(arr_mean)

[0.70069121 0.87982001 0.0883828  0.30791313 0.20457196 0.78076888
 0.85412706 0.38169013 0.56852131 0.47731512 0.81121461 0.6461879
 0.74412025 0.30560411 0.03873063 0.73540852 0.3070355  0.6087471
 0.76779431 0.1270935  0.82237687 0.52478042 0.3173319  0.46056736
 0.37958529 0.91354656 0.46722517 0.48609511 0.98321262 0.30939173]
0.5333283683508503


 15. Create a 2d array with 1 on the border and 0 inside

In [26]:
arr=np.ones((10,10))
arr[1:-1,1:-1]=0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? 

In [28]:
arr = np.ones((6,6))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(arr)


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

In [30]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
arr=np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


 19. Create a 8x8 matrix and fill it with a checkerboard pattern 

In [32]:
arr = np.zeros((8,8),dtype=int)
arr[1::2,::2] = 1
arr[::2,1::2] = 1
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [33]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


 21. Create a checkerboard 8x8 matrix using the tile function

In [34]:
arr = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(arr)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 22. Normalize a 5x5 random matrix 

In [36]:
arr= np.random.random((5,5))
arr=(arr - np.mean(arr) / (np.std (arr)))
print(arr)

[[-1.60135233 -0.75591933 -1.36310807 -1.50373916 -1.14981789]
 [-1.38057753 -1.54837095 -1.48663948 -1.35521313 -1.38173385]
 [-0.98629932 -1.10461478 -1.21901851 -1.3248297  -0.85989613]
 [-0.73266249 -1.31476961 -1.34548782 -0.98213992 -1.2342822 ]
 [-0.89412327 -0.79448521 -1.70548427 -1.62131932 -1.47554213]]


23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [40]:
arr1=np.ones((5,3))
arr2=np.ones((3,2))
prd=np.dot(arr1,arr2)
print(prd)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [41]:
arr=np.arange(11)
arr[(3<arr) & (arr < 8)] *=-1
print(arr)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


26. What is the output of the following script? (★☆☆)

# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [51]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


28. What are the result of the following expressions? (★☆☆)

In [50]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\PC\AppData\Local\Temp\ipykernel_1388\3912170336.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


29. How to round away from zero a float array ? (★☆☆)

In [52]:
arr = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr)), arr))

[ 6.  5. -9. -4. -9. -6. -1. 10.  4. -9.]


30. How to find common values between two arrays? (★☆☆)

In [53]:
arr1 = np.random.randint(0,10,10)
arr2 = np.random.randint(0,10,10)
print(np.intersect1d(arr1,arr2))

[0 2 4 5 7 8]
